### ISSUE TITLE
Add "main" module for command line usage

### ISSUE THREAD

**Issue by DarkSearchApp** [thehappydinoa/DarkSearch#1]
Thanks for your amazing work ! I (lead developper of DarkSearch) am currently working on a PR with some minor changes. 

However, I think that it would be a good idea to add a main function and module in order for your API client to be used from the command line. 

With this features, it would be possible for everyone (not just python programmers) to integrate with you lib and use you it in bash scripts too. What do you think of this idea ?

**Comment by thehappydinoa** [comment]
@DarkSearchApp I like that idea quite a lot.

**Comment by DarkSearchApp** [comment]
When do you think it would be possible to implement this ?

**Comment by thehappydinoa** [comment]
Added in 71c3cc7 or `1.5.0`
